version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test1
    ports:
    - 3307:3307
    networks:
      - netmysql
    volumes:
    - ./data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    networks:
      - netmysql
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80

  spring:
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - db
    ports:
    - 8080:8080
    networks:
      - netmysql


networks:
  netmysql: